language: c
sudo: false
before_script: autoreconf --install
addons:
  apt:
    packages:
    - check
install:
  - ./ci/install-dependencies.sh
script: CFLAGS="-I`pwd`/Criterion/include" LDFLAGS="-L`pwd`/Criterion/build -Wl,-R -Wl,`pwd`/Criterion/build" ./configure && make && make check


