language: c
before_script: autoreconf --install
install:
  - sudo apt-get install check
  - ./ci/install-dependencies.sh
script: CFLAGS="-I`pwd`/Criterion/include" ./configure && make && LD_LIBRARY_PATH="`pwd/Criterion/build" make check


