language: c
compiler:
  - clang
  - gcc
sudo: false
before_script: autoreconf --install
addons:
  apt:
    packages:
    - check
install:
  - ./ci/install-dependencies.sh
script: CFLAGS="-std=gnu99 -Wall -Wextra -Werror -I`pwd`/Criterion/include" LDFLAGS="-L`pwd`/Criterion/build -Wl,-R -Wl,`pwd`/Criterion/build" ./configure && make && make check
