language: c
before_script: autoreconf --install
install:
  - sudo apt-get install check
  - ./ci/install-dependencies.sh
  - export LD_LIBRARY_PATH="`pwd`/Criterion/build"
script: CFLAGS="-I`pwd`/Criterion/include" ./configure && make && make check


