language: c
before_script: autoreconf --install
install:
  - sudo apt-get install check
  - ./ci/install-dependencies.sh
script: CFLAGS="-ICriterion/include" LDFLAGS="-LCriterion/build" ./configure && make && make check


