language: c
before_script: autoreconf --install
install:
  - sudo apt-get install check
  - ./ci/install-dependencies.sh
script: CFLAGS="-I`pwd`/Criterion/include" LDFLAGS="-L`pwd`/Criterion/build" ./configure && make && make check


